name: Deploy Codeigniter API

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        working-directory: ./codeigniter
        run: composer install --prefer-dist

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3
        with:
          name: codeigniter-artifact
          path: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: codeigniter-artifact

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/bible/api/
